version: "3.8"
services:
  robot:
    image: robot:latest
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/ws/
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # - /run/udev:/run/udev:ro
      # - /opt/vc:/opt/vc
      # - /etc/apt/trusted.gpg.d/:/etc/apt/trusted.gpg.d/
      - /dev/shm:/dev/shm
      - /dev/input:/dev/input
      - /dev/bus/usb:/dev/bus/usb
      - /dev/input:/dev/input
    environment:
      # - DISPLAY=${DISPLAY}
      # - DISPLAY=192.168.128.1:0.0
      - ROS_DOMAIN_ID=0
      # - ROS_DISCOVERY_SERVER=192.168.1.167:11811
    devices:
      - /dev/dri:/dev/dri
      - /dev/input/js0:/dev/input/js0
      - /dev/input/event0:/dev/input/event0
    # runtime: nvidia
    stdin_open: true
    tty: true
    privileged: true
    network_mode: "host"
    

